import { ShieldCheck, Info, Scale, Lock, AlertTriangle } from 'lucide-react';

export default function LegalPage() {
  const sections = [
    { 
      title: "Terms of Service", 
      icon: <Scale size={20} className="text-blue-600" />,
      content: "ProductFlowAI provides a platform for business inspiration and strategy. By using this site, you agree that we are not responsible for any business losses or decisions made based on AI output. Users must be 18+ to purchase toolkit resources." 
    },
    { 
      title: "Privacy Policy", 
      icon: <Lock size={20} className="text-emerald-600" />,
      content: "We value your privacy. Your data is encrypted via SSL. We do not sell user data. Payment processing is handled entirely by Stripe; we never see or store your full credit card details." 
    },
    { 
      title: "AI & Medical Disclaimer", 
      icon: <AlertTriangle size={20} className="text-amber-600" />,
      content: "Our AI suggestions are generated by algorithms. They are NOT a substitute for professional medical, legal, or financial advice. We do not guarantee income. Always consult a certified professional before investing capital." 
    }
  ];

  return (
    <div className="max-w-4xl mx-auto py-32 px-6">
      <h1 className="text-5xl font-black text-slate-900 mb-4 tracking-tight">Legal & Compliance</h1>
      <p className="text-slate-500 mb-12 text-lg">Last Updated: March 16, 2026</p>
      
      <div className="space-y-12">
        {sections.map((section, i) => (
          <div key={i} className="p-8 rounded-[2rem] border border-slate-100 bg-slate-50/50">
            <div className="flex items-center gap-3 mb-4">
              {section.icon}
              <h2 className="text-xl font-black text-slate-900">{section.title}</h2>
            </div>
            <p className="text-slate-600 leading-relaxed font-medium">{section.content}</p>
          </div>
        ))}
      </div>
    </div>
  );
}

